version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    networks:
      - backend
    restart: always 
  
networks:
  backend:
    driver: bridge