# syntax=docker/dockerfile:1

FROM python:3.10

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt

COPY . /app

ARG REDIS_URL

ENV REDIS_URL $REDIS_URL

CMD ["rqscheduler", "--url",  "$REDIS_URL"]