version: '3'
services:
  web:
    build: .
    ports:
        - "8080:8080"
    volumes:
        - .:/app
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    networks:
      - backend
    restart: always
  
networks:
  backend:
    driver: bridge