# syntax=docker/dockerfile:1

FROM python:3.10

ARG REDIS_URL

ENV REDIS_URL_ENV ${REDIS_URL}

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt

COPY . /app

CMD ["rqscheduler", "--url",  "${REDIS_URL_ENV}"]