version: 2.1
orbs:
  orb-tools: circleci/orb-tools@8.26.0
commands:
  doctl_initialize:
    description: Initilize the digitalocean CLI
    parameters:
      digitalocean-access-token:
        default: DIGITALOCEAN_ACCESS_TOKEN
        description: |
          Name of environment variable storing the digitalocean v2 api access token
        type: env_var_name
    steps:
      - run:
          command: |
            doctl auth init -t $<<parameters.digitalocean-access-token>>
          name: Initialize doctl
  doctl_install:
    description: Install the doctl, if not available
    steps:
      - run: 
          command: |
            cat /etc/os-release
      - run: 
          command: |
            apk update
            apk upgrade --available
            apk --no-cache add doctl
      - run: 
          command: |
            doctl version     
jobs:
  build:
    working_directory: /app
    parameters:
      digitalocean-access-token:
        default: DIGITALOCEAN_ACCESS_TOKEN
        description: The access token to connect DigitalOcean
        type: env_var_name
    docker:
      - image: docker:20.10.18-git
        environment:
          FCM_TOKEN: $FCM_TOKEN
          FERNET_KEY: $FERNET_KEY
          JWT_TOKEN: $JWT_TOKEN
          MONGO_URI: $MONGO_URI
          REDIS_URL: $REDIS_URL
          ENV_MODE: $ENV_MODE
    steps:
      - checkout
      - setup_remote_docker
      - doctl_install
      - doctl_initialize:
          digitalocean-access-token: <<parameters.digitalocean-access-token>>
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t gradebook-web .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar gradebook-web
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - run:
          name: Initialize doctl
          command: |
            doctl auth init -t $<<parameters.digitalocean-access-token>>
      - run:
          name: Login to Registry
          command: |
            doctl registry login
      - run: 
          name: push gradebook-web image 
          command: |
            docker tag gradebook-web "registry.digitalocean.com/genesus/gradebook-web"
            docker push "registry.digitalocean.com/genesus/gradebook-web"
      
      
workflows:
  build_and_deploy:
    jobs:
      - build
        